# Generated by Django 4.2.6 on 2023-10-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviw',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
    ]
