# Generated by Django 4.2.6 on 2023-10-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_reviw_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviw',
            old_name='reating',
            new_name='rating',
        ),
    ]
